[package]
name = "spm-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
spm-core = { path = "../spm-core" }
clap = "4.5.8"
env_logger = "0.11.3"
tokio = { version = "1.38.0", features = ["full"] }
